---
# Github Actions build for dupluxy
# -*- compile-command: "yamllint -f parsable build.yml" -*-

name: build
on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
  workflow_dispatch:
    inputs:
      manual:
        description: Manual run (bypass default conditions)
        type: boolean
        required: true
        default: true
jobs:
  build:
    # if: ${{ github.event.inputs.manual == 'true' || (github.repository == 'dupluxy/dupluxy' && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name )) }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        job_name: ['linux']

        include:
          - job_name: linux
            os: ubuntu-latest
            go: '1.21.6'

    name: ${{ matrix.job_name }}
    runs-on: {{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          check-latest: true

      - name: Print environment variables
        shell: bash
        run: |
          printf "Using go: $(which go)\n"
          printf "Using go version: $(go version)\n"
          printf "\n\nGo environment variables:\n"
          go env
          printf  "\n\nSystem environment variables:\n"
          env

      - name: Go module cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build dupluxy
        shell: bash
        run: |
          make build-all

      - name: Deploy built binaries
        uses: actions/upload-artifact@v2
        with:
          name: dupluxy-binaries
          path: out/dupluxy_*
